"""Contrastive proxy-task training entry point."""

import argparse
import copy
import glob
import logging
import os
import time

import torch
import torch.nn

try:
    from torchinfo import summary
except Exception:  # torchinfo is optional for public reruns
    summary = None

import dataloader
from models.resnet_oth import SimCLR, SimSiam, simsiam_loss, nt_xent_loss, ResNetBack


os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train SimCLR or SimSiam proxy models on stored augmentations.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--epochs", type=int, default=200, help="number of epochs of training")
    parser.add_argument("--target_class", type=str, default="ToyCar", help="single target class to train")
    parser.add_argument("--target_classes", nargs="+", default=None,
                        help="deprecated compatibility sweep; public contrastive runs are global-like")
    parser.add_argument("--mode", type=str, default="simclr", choices=["simclr", "simsiam"])
    parser.add_argument("--save_model_dir", type=str, default="./saved_exp/contrastive", help="dir of saved model")
    parser.add_argument("--batch_size", type=int, default=96)
    parser.add_argument("--n_cpu", type=int, default=32)
    parser.add_argument("--input_len", type=int, default=160000)
    parser.add_argument("--decay_epoch", type=int, default=50, help="epoch from which to start lr decay")
    parser.add_argument("--test_name", type=str, default=None, help="checkpoint name prefix")
    parser.add_argument("--resnet", type=str, default="resnet152",
                        choices=["resnet18", "resnet34", "resnet50", "resnet101", "resnet152"])
    parser.add_argument("--resnets", nargs="+", default=None,
                        choices=["resnet18", "resnet34", "resnet50", "resnet101", "resnet152"],
                        help="optional explicit ResNet list")
    parser.add_argument("--init_lr", type=float, default=5e-4, help="initial learning rate")
    parser.add_argument("--target_dir", type=str, default="./asd_dataset_logmel", help="dir of dataset")
    parser.add_argument(
        "--matrix_log_mode",
        type=str,
        default="auto",
        choices=["auto", "raw", "already_log", "log", "db", "none"],
        help=(
            "Scale handling for logmel npy files. Use auto/raw for raw "
            "mel-power generated by prepare_dataset_features.py --logmel-mode raw."
        ),
    )
    parser.add_argument(
        "--segment_frames",
        type=int,
        default=313,
        help="fixed frame length for contrastive npy tensors; 313 matches 10 s audio with hop 512 at 16 kHz",
    )
    parser.add_argument(
        "--random_crop",
        action="store_true",
        help="randomly crop variable-length contrastive features instead of center-cropping",
    )
    parser.add_argument("--margin", type=float, default=0.5, help="negative contrastive margin")
    parser.add_argument("--save_interval", type=int, default=5,
                        help="save epoch checkpoint every N epochs. Set 0 or negative to disable.")
    parser.add_argument("--prune_previous_best", action="store_true",
                        help="delete the previous best checkpoint when a new best is saved")
    parser.add_argument("--cuda_visible_devices", default=None,
                        help="optional CUDA_VISIBLE_DEVICES value for this run")
    parser.add_argument("--device", default="auto",
                        help="torch device, e.g. auto, cuda:0, or cpu")
    parser.add_argument("--print_summary", action="store_true",
                        help="print torchinfo model summary when torchinfo is installed")
    parser.add_argument("--legacy_accumulate_gradients", action="store_true",
                        help="preserve the previous behavior that accumulated gradients across batches")
    return parser.parse_args()


def iter_target_classes(args: argparse.Namespace) -> list[str]:
    return args.target_classes if args.target_classes is not None else [args.target_class]


def iter_resnets(args: argparse.Namespace) -> list[str]:
    return args.resnets if args.resnets is not None else [args.resnet]


def configure_runtime(args: argparse.Namespace) -> None:
    if args.cuda_visible_devices is not None:
        os.environ["CUDA_VISIBLE_DEVICES"] = str(args.cuda_visible_devices)


def resolve_device(device_arg: str) -> torch.device:
    if str(device_arg).lower() == "auto":
        return torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    if str(device_arg).startswith("cuda") and not torch.cuda.is_available():
        logging.warning("CUDA requested but not available. Falling back to CPU.")
        return torch.device("cpu")
    return torch.device(device_arg)


def maybe_print_summary(model, input_size, args) -> None:
    if not args.print_summary:
        return
    if summary is None:
        logging.warning("torchinfo is not installed; skip summary.")
        return
    try:
        summary(model, input_size)
    except Exception as exc:
        logging.warning(f"torchinfo.summary failed: {exc}")


class Trainer:
    def __init__(self, train_ds, device: torch.device):
        self.train_ds = train_ds
        self.gpu_id = device

    def train(self, model, loader, args):
        if len(loader) == 0:
            raise RuntimeError("Contrastive DataLoader is empty. Check augmentation pairs and batch size.")

        optimizer = torch.optim.AdamW(model.parameters(), lr=args.init_lr)
        scheduler = torch.optim.lr_scheduler.StepLR(
            optimizer, step_size=args.decay_epoch, gamma=0.5
        )
        best_loss = float("inf")
        best_model_weights = None
        best_epoch = None
        best_save_path = None
        save_name_prefix = f"{args.test_name}_batch{args.batch_size}_m{args.margin}"

        for epoch in range(args.epochs):
            if args.legacy_accumulate_gradients:
                optimizer.zero_grad()
            epoch_num = epoch + 1
            st_time = time.time()

            train_loss = 0.0

            for data in loader:

                aug0 = data[0].to(self.gpu_id)
                aug1 = data[1].to(self.gpu_id)

                if not args.legacy_accumulate_gradients:
                    optimizer.zero_grad()
                if args.mode == 'simclr':
                    aug0_out = model(aug0)
                    aug1_out = model(aug1)
                    loss = nt_xent_loss(aug0_out, aug1_out, temperature=0.1)  # default 0.1 at original paper
                else:
                    p0, z1, p1, z0 = model(aug0, aug1)
                    loss = simsiam_loss(p0, z1, p1, z0)

                loss.backward()
                train_loss += loss.item()
                optimizer.step()

            train_loss = train_loss / len(loader)
            scheduler.step()

            is_best = train_loss < best_loss
            if is_best:
                best_loss = train_loss
                best_epoch = epoch_num

                # Keep only the latest best-loss checkpoint for this run.
                if args.prune_previous_best and best_save_path is not None and os.path.exists(best_save_path):
                    os.remove(best_save_path)

                best_save_path = os.path.join(
                    args.save_model_dir,
                    f"{save_name_prefix}_best_epoch{epoch_num:03d}_loss{best_loss:.8f}.pth"
                )
                torch.save(model.state_dict(), best_save_path)
                best_model_weights = copy.deepcopy(model.state_dict())
                logging.info(f"Saved best model: {best_save_path}")

            if args.save_interval > 0 and epoch_num % args.save_interval == 0:
                epoch_save_path = os.path.join(
                    args.save_model_dir,
                    f"{save_name_prefix}_epoch{epoch_num:03d}_loss{train_loss:.8f}.pth"
                )
                torch.save(model.state_dict(), epoch_save_path)
                logging.info(f"Saved interval model: {epoch_save_path}")

            logging.info(
                f'{epoch_num} epoch, {(str(time.time() - st_time))[:5]}seconds')
            logging.info(
                f'{epoch_num} epoch, loss : {(str(train_loss))[:5]}, best : {(str(best_loss))[:5]}')

        if best_model_weights is not None:
            model.load_state_dict(best_model_weights)
            logging.info(
                f'Unsupervised train finished. Best epoch={best_epoch}, '
                f'best loss={best_loss:.8f}, best model={best_save_path}'
            )
        else:
            logging.info('Unsupervised train finished, but no epoch was trained; no best model was saved.')

    def main_tr(self, args):

        resnet = ResNetBack(resnet_type=args.resnet)
        if args.mode == 'simclr':
            if args.resnet in ['resnet18', 'resnet34']:
                model = SimCLR(resnet, proj_hidden_dim=512)
            else:
                model = SimCLR(resnet, proj_hidden_dim=2048)
            maybe_print_summary(model, [(1, 1, 128, args.segment_frames)], args)
        else:
            if args.resnet in ['resnet18', 'resnet34']:
                model = SimSiam(resnet, proj_hidden_dim=512, proj_out_dim=512)
            else:
                model = SimSiam(resnet, proj_hidden_dim=2048, proj_out_dim=2048)

        self.train(model.to(self.gpu_id), self.train_ds, args)


def main(rank: int, world_size: int, args):
    os.makedirs(args.save_model_dir, exist_ok=True)

    if args.mode not in ["simclr", "simsiam"]:
        raise ValueError(f"args.mode must be 'simclr' or 'simsiam', but got: {args.mode}")

    logging.info(args)
    device = resolve_device(args.device)

    dirs = sorted(glob.glob(os.path.abspath("{base}/*".format(base=args.target_dir))))
    dirs = [f for f in dirs if os.path.isdir(f)]

    class_list = [os.path.basename(f) for f in dirs]

    train_ds = dataloader.class_data_contrastive(
        args.target_dir, args.batch_size, args.n_cpu
        , args.target_class, class_list=class_list, snr_list=[3, 4, 5, 6, 7, 8, 9, 10],
        matrix_log_mode=args.matrix_log_mode,
        segment_frames=args.segment_frames,
        random_crop=args.random_crop,
    )
    trainer = Trainer(train_ds, device)
    trainer.main_tr(args=args)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    args = parse_args()
    configure_runtime(args)
    if args.target_classes is not None:
        logging.warning(
            "--target_classes for train_contrastive.py is deprecated. "
            "The public contrastive grid is global-like and should be launched once. "
            "Use --target_class only for legacy-compatible naming."
        )
    for target_class in iter_target_classes(args):
        for resnet in iter_resnets(args):
            run_args = copy.copy(args)
            run_args.target_class = target_class
            run_args.resnet = resnet
            run_args.test_name = args.test_name or f"{args.mode}_{resnet}"
            main(rank=0, world_size=0, args=run_args)
